[rospy.client][INFO] 2017-10-13 16:43:01,003: init_node, name[/robot_1/client_node], pid[6235]
[xmlrpc][INFO] 2017-10-13 16:43:01,005: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-13 16:43:01,005: Started XML-RPC server [http://wks-51-57:40910/]
[rospy.impl.masterslave][INFO] 2017-10-13 16:43:01,005: _ready: http://wks-51-57:40910/
[rospy.registration][INFO] 2017-10-13 16:43:01,006: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-10-13 16:43:01,006: ROS Slave URI: [http://wks-51-57:40910/]
[rospy.init][INFO] 2017-10-13 16:43:01,006: registered with master
[rospy.rosout][INFO] 2017-10-13 16:43:01,006: initializing /rosout core topic
[xmlrpc][INFO] 2017-10-13 16:43:01,009: xml rpc node: starting XML-RPC server
[rospy.rosout][INFO] 2017-10-13 16:43:01,012: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-13 16:43:01,013: initializing /clock core topic
[rospy.simtime][INFO] 2017-10-13 16:43:01,016: connected to core topic /clock
[rospy.internal][INFO] 2017-10-13 16:43:01,062: topic[/tf] adding connection to [http://wks-51-57:37181/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,064: topic[/tf] adding connection to [http://wks-51-57:40214/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,066: topic[/tf] adding connection to [http://wks-51-57:40077/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,071: topic[/collision_positions] adding connection to [http://wks-51-57:42036/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,088: topic[/navigation_activity_status] adding connection to [http://wks-51-57:42036/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,093: topic[/navigation_activity_status] adding connection to [http://wks-51-57:40910/], count 1
[rospy.internal][INFO] 2017-10-13 16:43:01,094: topic[/navigation_activity_status] adding connection to [/robot_1/client_node], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,148: topic[/navigation_activity_status] adding connection to [/robot_0/client_node], count 1
[rospy.internal][INFO] 2017-10-13 16:43:01,150: topic[/collision_positions] adding connection to [/robot_0/client_node], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,158: topic[/collision_positions] adding connection to [http://wks-51-57:40910/], count 1
[rospy.internal][INFO] 2017-10-13 16:43:01,161: topic[/collision_positions] adding connection to [/robot_1/client_node], count 1
[rospy.internal][INFO] 2017-10-13 16:43:01,234: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,372: topic[/clock] adding connection to [http://wks-51-57:40214/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,372: topic[/robot_1/base_pose_ground_truth] adding connection to [http://wks-51-57:40214/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:03,536: topic[/robot_1/move_base/status] adding connection to [http://wks-51-57:41233/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:03,538: topic[/robot_1/move_base/feedback] adding connection to [http://wks-51-57:41233/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:03,538: topic[/robot_1/move_base/result] adding connection to [http://wks-51-57:41233/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:03,639: topic[/robot_1/move_base/goal] adding connection to [/robot_1/move_base_node], count 0
[rospy.internal][INFO] 2017-10-13 16:43:03,639: topic[/robot_1/move_base/cancel] adding connection to [/robot_1/move_base_node], count 0
[rospy.internal][INFO] 2017-10-13 16:43:38,575: topic[/robot_status] adding connection to [/coordinator_8334_1507905818501], count 0
[rospy.internal][INFO] 2017-10-13 16:44:42,781: topic[/robot_1/patrol_status] adding connection to [/coordinator_8334_1507905818501], count 0
[rospy.internal][INFO] 2017-10-13 16:44:42,870: topic[/robot_1/coordinator_directions] adding connection to [http://wks-51-57:44690/], count 0
[rosout][ERROR] 2017-10-13 16:44:42,871: ************************
[rosout][ERROR] 2017-10-13 16:44:42,871: robot_1
[rosout][ERROR] 2017-10-13 16:44:42,872: sending a goal 1.0 2.0
[rosout][ERROR] 2017-10-13 16:44:51,157: robot_1
[rosout][ERROR] 2017-10-13 16:44:51,158: done cb
[rosout][INFO] 2017-10-13 16:44:51,158: 3
[rosout][ERROR] 2017-10-13 16:45:32,851: ************************
[rosout][ERROR] 2017-10-13 16:45:32,851: robot_1
[rosout][ERROR] 2017-10-13 16:45:32,851: sending a goal 1.0 2.0
[rosout][ERROR] 2017-10-13 16:45:32,886: robot_1
[rosout][ERROR] 2017-10-13 16:45:32,886: done cb
[rosout][INFO] 2017-10-13 16:45:32,886: 3
[rosout][ERROR] 2017-10-13 16:45:32,888: ************************
[rosout][ERROR] 2017-10-13 16:45:32,888: robot_1
[rosout][ERROR] 2017-10-13 16:45:32,888: sending a goal 2.0 4.0
[rospy.internal][ERROR] 2017-10-13 16:45:38,192: Unable to initiate TCP/IP socket to wks-51-57:39050 (http://wks-51-57:44690/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-10-13 16:45:39,193: Unknown error initiating TCP/IP socket to wks-51-57:39050 (http://wks-51-57:44690/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-10-13 16:45:39,193: topic[/robot_1/coordinator_directions] removing connection to http://wks-51-57:44690/
[rosout][ERROR] 2017-10-13 16:45:41,885: robot_1
[rosout][ERROR] 2017-10-13 16:45:41,885: done cb
[rosout][INFO] 2017-10-13 16:45:41,885: 4
[rospy.core][INFO] 2017-10-13 16:45:45,170: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-13 16:45:45,186: topic[/robot_1/patrol_status] removing connection to /coordinator_8334_1507905818501
[rospy.internal][INFO] 2017-10-13 16:45:45,186: topic[/robot_1/move_base/cancel] removing connection to /robot_1/move_base_node
[rospy.internal][INFO] 2017-10-13 16:45:45,186: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-13 16:45:45,186: topic[/robot_status] removing connection to /coordinator_8334_1507905818501
[rospy.internal][INFO] 2017-10-13 16:45:45,187: topic[/robot_1/move_base/goal] removing connection to /robot_1/move_base_node
[rospy.internal][INFO] 2017-10-13 16:45:45,187: topic[/navigation_activity_status] removing connection to /robot_1/client_node
[rospy.internal][INFO] 2017-10-13 16:45:45,187: topic[/navigation_activity_status] removing connection to /robot_0/client_node
[rospy.internal][INFO] 2017-10-13 16:45:45,187: topic[/collision_positions] removing connection to /robot_0/client_node
[rospy.internal][INFO] 2017-10-13 16:45:45,188: topic[/collision_positions] removing connection to /robot_1/client_node
[rospy.internal][ERROR] 2017-10-13 16:45:45,189: Unable to initiate TCP/IP socket to wks-51-57:35111 (http://wks-51-57:40910/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-13 16:45:45,190: Unable to initiate TCP/IP socket to wks-51-57:35111 (http://wks-51-57:40910/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-13 16:45:45,190: topic[/robot_1/base_pose_ground_truth] removing connection to http://wks-51-57:40214/
[rospy.internal][ERROR] 2017-10-13 16:45:45,190: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][ERROR] 2017-10-13 16:45:45,191: Unable to initiate TCP/IP socket to wks-51-57:42407 (http://wks-51-57:42036/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-13 16:45:45,191: Unable to initiate TCP/IP socket to wks-51-57:42407 (http://wks-51-57:42036/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-13 16:45:45,191: topic[/robot_1/move_base/result] removing connection to http://wks-51-57:41233/
[rospy.internal][INFO] 2017-10-13 16:45:45,191: topic[/tf] removing connection to http://wks-51-57:37181/
[rospy.internal][INFO] 2017-10-13 16:45:45,191: topic[/tf] removing connection to http://wks-51-57:40214/
[rospy.internal][INFO] 2017-10-13 16:45:45,192: topic[/tf] removing connection to http://wks-51-57:40077/
[rospy.internal][INFO] 2017-10-13 16:45:45,192: topic[/clock] removing connection to http://wks-51-57:40214/
[rospy.internal][WARNING] 2017-10-13 16:45:45,192: Unknown error initiating TCP/IP socket to wks-51-57:49725 (http://wks-51-57:40214/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-13 16:45:45,192: topic[/robot_1/move_base/feedback] removing connection to http://wks-51-57:41233/
[rospy.internal][INFO] 2017-10-13 16:45:45,192: topic[/navigation_activity_status] removing connection to http://wks-51-57:42036/
[rospy.internal][INFO] 2017-10-13 16:45:45,193: topic[/navigation_activity_status] removing connection to http://wks-51-57:40910/
[rospy.internal][INFO] 2017-10-13 16:45:45,193: topic[/collision_positions] removing connection to http://wks-51-57:42036/
[rospy.internal][INFO] 2017-10-13 16:45:45,193: topic[/collision_positions] removing connection to http://wks-51-57:40910/
[rospy.internal][INFO] 2017-10-13 16:45:45,193: topic[/robot_1/move_base/status] removing connection to http://wks-51-57:41233/
[rospy.internal][WARNING] 2017-10-13 16:45:45,193: Unknown error initiating TCP/IP socket to wks-51-57:36270 (http://wks-51-57:41233/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2017-10-13 16:45:45,193: signal-2
[rospy.internal][WARNING] 2017-10-13 16:45:45,201: Unknown error initiating TCP/IP socket to wks-51-57:36270 (http://wks-51-57:41233/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2017-10-13 16:45:45,252: Unknown error initiating TCP/IP socket to wks-51-57:36265 (http://wks-51-57:40077/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2017-10-13 16:45:45,809: signal_shutdown [atexit]
